# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: M

# SEO

# TODO adjust this file

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'Our cool Todo4NFDI service'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    show_theme_chooser: true
    highlight_active_link: true
    logo:
      text: ""
      filename: "logo.png"

# Site footer

footer:
  about: '[Base4NFDI](https://www.base4nfdi.de), Funded by DFG as part of [NFDI](https://www.nfdi.de).<br>
    <a href="https://github.com/your-github-username" target="_blank" rel="noopener noreferrer">
      <i class="fab fa-github fa-lg text-white"></i>
    </a>'
  mission: 'Base4NFDI<br>
        [What is Base4NDFI?](https://www.base4nfdi.de)<br>
        [What is a Basic Service?](https://www.base4nfdi.de)<br>
        [Our Mission Statement](https://www.base4nfdi.de)'
  dfg: '<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	      viewBox="0 0 425.2 267.87" style="enable-background:new 0 0 425.2 267.87;" xml:space="preserve">
        <style type="text/css">
          .st0{fill:none;}
          .st1{fill:#B3BCC2;}
          .st2{fill:#FFFFFF;}
          .st3{fill:#0BBBEF;}
          .st4{fill:#A2C617;}
          .st5{fill:#8A959C;}
          .st6{fill:#45556A;}
        </style>
        <rect x="0" class="st0" width="425.2" height="267.87"/>
        <path class="st2" d="M220.66,70.87c-22.97,0-41.65,18.68-41.65,41.65v76.35c0,4.49,3.64,8.13,8.13,8.13c4.49,0,8.13-3.64,8.13-8.13
          v-50.61h12.86c4.18,0,7.57-3.46,7.57-7.73c0-4.27-3.39-7.73-7.57-7.73h-12.86v-10.28c0-14,11.39-25.39,25.39-25.39
          c4.49,0,8.13-3.64,8.13-8.13S225.15,70.87,220.66,70.87"/>
        <g>
          <path class="st2" d="M147.31,196.99c-4.49,0-8.13-3.64-8.13-8.13l0.06-33.76c0-14-11.39-25.39-25.39-25.39
            s-25.39,11.39-25.39,25.39c0,4.49-3.64,8.13-8.13,8.13s-8.13-3.64-8.13-8.13c0-22.96,18.68-41.65,41.65-41.65
            s41.65,18.68,41.65,41.65v33.76C155.5,193.35,151.8,196.99,147.31,196.99"/>
          <path class="st3" d="M89.8,187.5c0,5.23-4.24,9.47-9.47,9.47c-5.23,0-9.47-4.24-9.47-9.47s4.24-9.47,9.47-9.47
            C85.56,178.03,89.8,182.27,89.8,187.5"/>
        </g>
        <g>
          <path class="st4" d="M351.91,95.15c3.49,3.89,3.17,9.88-0.72,13.37c-3.89,3.49-9.88,3.16-13.37-0.73
            c-3.49-3.89-3.17-9.88,0.72-13.37C342.43,90.93,348.42,91.25,351.91,95.15"/>
          <path class="st2" d="M352.99,133.86v55c0,4.49-3.64,8.13-8.13,8.13l0,0c-4.49,0-8.13-3.64-8.13-8.13v-55
            c0-4.49,3.64-8.13,8.13-8.13h0C349.36,125.73,352.99,129.37,352.99,133.86z"/>
        </g>
        <path class="st2" d="M304.88,70.87c-4.49,0-8.13,3.64-8.13,8.13v43.2c-7.06-5.47-15.91-8.73-25.51-8.73
          c-23.03,0-41.77,18.73-41.77,41.76s18.73,41.76,41.77,41.76c23.03,0,41.76-18.73,41.76-41.76V79
          C313,74.51,309.37,70.87,304.88,70.87z M271.24,180.74c-14.07,0-25.51-11.44-25.51-25.51c0-14.06,11.44-25.51,25.51-25.51
          c14.06,0,25.51,11.44,25.51,25.51C296.74,169.3,285.3,180.74,271.24,180.74z"/>
        </svg>
        <img src="media/dfg_logo_schriftzug_neg_4c.png" alt="Your Image" class="img-fluid">
        <p class="powered-by">
          Grant Numbers: 521453681, 521460392, 521462155, 521463400, <br> 521466146, 521471126, 521473512, 521474032, 521475185, 521476232. 
        </p>'
  copyright:
    notice: '© {year} Todo4NFDI,  This work is licensed under {license} <br> <br>
    [Privacy](https://www.base4nfdi.de) | [Legal Note](https://www.base4nfdi.de) | [Accessibility](https://www.base4nfdi.de) '
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true


# Localization

locale:
  date_format: '_2 January 2006'
  time_format: '15:04'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/base4nfdi/website-template-hugo'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa